routes/web.php
<?php

// Admin Panel
Route::namespace('Admin')->prefix('admin')->middleware(['auth:web','admin','lastLogin'])->group(function () {
    Route::get('dashboard','AdminController@index')->name('adminDashboard');
    // Projects
    Route::resource('projects','ProjectController');
    Route::get('project/pending','ProjectController@pending')->name('projects.pending');
    Route::get('project/canceled','ProjectController@canceled')->name('projects.canceled');
    Route::get('project/closed','ProjectController@closed')->name('projects.closed');
    Route::patch('projects/active/{project}','ProjectController@confirm')->name('project.active');
    Route::patch('projects/deactivate/{project}','ProjectController@deactivate')->name('project.deactivate');
    Route::get('project/search','ProjectController@search')->name('projects.search');
    Route::post('project/search','ProjectController@searchPost')->name('projects.search.post');
    Route::delete('projects/offer/{offer}/delete','ProjectController@deleteOffer')->name('project.offer.delete');
    Route::patch('projects/offer/{offer}/assign','ProjectController@assign')->name('project.offer.assign');
    // Category
    Route::resource('categories','CategoryController');
    // Skills
    Route::resource('skills','SkillController');
    // Packages
    Route::resource('packages','PackageController');
    // Links
    Route::resource('links','LinkController');
    // Payment
    Route::get('payments','PaymentController@index')->name('payments.index');
    Route::get('payments/unsuccessful','PaymentController@unsuc')->name('payments.unsuc');
    Route::get('payments/successful','PaymentController@suc')->name('payments.suc');
    Route::get('payments/deposits','PaymentController@deposits')->name('payments.deposits');
    Route::get('payments/release','PaymentController@release')->name('payments.release');
    Route::get('withdraws','PaymentController@withdraws')->name('withdraws.index');
    Route::get('withdraws/pending','PaymentController@pending')->name('withdraws.pending');
    Route::get('withdraws/successful','PaymentController@successful')->name('withdraws.suc');
    Route::get('withdraws/canceled','PaymentController@canceled')->name('withdraws.canceled');
    Route::get('withdraws/{withdraw}','PaymentController@view')->name('withdraws.view');
    Route::patch('withdraws/{withdraw}','PaymentController@pay')->name('withdraws.pay');
    // Packages
    Route::resource('faqs','FaqController',['parameters' => [
        'faqs' => 'question'
    ]]);
    // Packages
    Route::resource('helps','HelpController',['parameters' => [
        'helps' => 'question'
    ]]);
    // Users
    Route::resource('users','UserController');
    Route::get('user/search','UserController@search')->name('users.search');
    Route::post('user/search','UserController@searchPost')->name('users.search.post');
    Route::patch('users/{user}/ban','UserController@ban')->name('users.ban');
    // Upload Files
    Route::group(['prefix'=>'uploadFile'],function (){
        // New Project
        Route::post('project','AdminController@projectUploadFile')->name('projectUploadFile');
    });
    // Site Settings
    Route::get('settings','SettingsController@index')->name('settings.index');
    Route::post('settings','SettingsController@update')->name('settings.update');
    // Site Settings
    Route::get('conversations','ConversationController@index')->name('conversation.index');
    Route::get('conversations/pending','ConversationController@pending')->name('conversation.pending');
    Route::get('conversations/rejected','ConversationController@rejected')->name('conversation.rejected');
    Route::patch('conversation/{conversation}/active','ConversationController@active')->name('conversation.active');
    Route::patch('conversation/{conversation}/reject','ConversationController@reject')->name('conversation.reject');
});

Route::namespace('User')->prefix('user')->middleware(['auth:web','lastLogin'])->group(function () {
    Route::get('dashboard','UserController@index')->name('userDashboard');
    // Project
    Route::get('project/new','ProjectController@index')->name('user.project.new');
    Route::post('project/new','ProjectController@store')->name('user.project.store');
    Route::get('project/{project}/edit','ProjectController@edit')->name('user.project.edit');
    Route::get('project/{project}/close','ProjectController@close')->name('user.project.close');
    Route::patch('project/{project}/update','ProjectController@update')->name('user.project.update');
    Route::post('project/new/categories','ProjectController@subcategory')->name('user.project.store.categories');
    Route::get('project/{project}','ProjectController@view')->name('user.project.view');
    // Deposit
    Route::get('project/{project}/deposits','ProjectController@deposit')->name('user.project.deposits');
    Route::patch('project/{project}/deposits','ProjectController@depositAction')->name('user.project.deposits.update');
    // Confirm
    Route::get('project/{project}/confirm','ProjectController@confirm')->name('project.confirm');
    // Release
    Route::get('project/{project}/release','ProjectController@release')->name('project.release');
    Route::patch('project/{project}/release','ProjectController@releaseAction')->name('project.release.update');
    // Make Vote
    Route::patch('project/{project}/vote','ProjectController@vote')->name('project.vote');
    // Project List
    Route::get('projects/all','ProjectController@all')->name('user.projects.all');
    Route::get('projects/urgent','ProjectController@urgent')->name('user.projects.urgent');
    Route::get('projects/special','ProjectController@special')->name('user.projects.special');
    Route::get('projects/related','ProjectController@related')->name('user.projects.related');
    Route::get('projects/hire','ProjectController@hire')->name('user.projects.hire');
    Route::get('projects/done','ProjectController@done')->name('user.projects.done');
    Route::post('projects/search','ProjectController@search')->name('user.projects.search');
    // Project Conversations Section
    Route::group(['prefix'=>'conversation'],function (){
        // Freelancer To Employer
        Route::get('/{project}','ProjectController@freelancerToEmployer')->name('conversations.fte');
        Route::post('/{project}','ProjectController@freelancerToEmployerStore')->name('conversations.fte.store');
        Route::get('/{project}/delete','ProjectController@freelancerToEmployerRemove')->name('conversations.fte.delete');
        // Employer To Freelancer
        Route::get('/{project}/{user}','ProjectController@employerToFreelancer')->name('conversations.etf');
        Route::post('/{project}/{user}','ProjectController@employerToFreelancerStore')->name('conversations.etf.store');
        // Accept Offer
        Route::patch('/{project}/{offer}/accept','ProjectController@acceptOffer')->name('project.accept.offer');
        // Pay Prepayment
        Route::get('/{project}/prepayment','ProjectController@employerPrepayment')->name('project.prepayment');
        // Pay Warranty
        Route::get('/{project}/warranty','ProjectController@freelancerWarranty')->name('project.warranty');
        // Convert To Hire
        Route::get('/{project}/make/hire','ProjectController@convertHire')->name('project.convert.hire');
        // Convert To Urgent
        Route::get('/{project}/make/urgent','ProjectController@convertUrgent')->name('project.convert.urgent');
        // Convert To Special
        Route::get('/{project}/make/special','ProjectController@convertSpecial')->name('project.convert.special');
        // Convert To Hidden
        Route::get('/{project}/make/hidden','ProjectController@convertHidden')->name('project.convert.hidden');
    });
    // Employer
    Route::get('employer/requests','EmployerController@index')->name('employer.requests');
    Route::post('employer/requests','EmployerController@filter')->name('employer.requests.filter');
    Route::get('employer/find','EmployerController@find')->name('employer.find');
    Route::post('employer/find','EmployerController@findFilter')->name('employer.find.filter');
    Route::get('employer/judgement','EmployerController@judge')->name('employer.judge');
    // Freelancer
    Route::get('freelancer/requests','FreelancerController@index')->name('freelancer.requests');
    Route::post('freelancer/requests','FreelancerController@filter')->name('freelancer.requests.filter');
    Route::get('freelancer/find','FreelancerController@find')->name('freelancer.find');
    Route::get('freelancer/judgement','FreelancerController@judge')->name('freelancer.judge');
    // Financial
    Route::group(['prefix'=>'financial'],function (){
        Route::get('/','FinancialController@index')->name('money.index');
        Route::get('/increase/credit','FinancialController@increase')->name('money.add');
        Route::get('/edit','FinancialController@edit')->name('money.edit');
        Route::post('/edit','FinancialController@store')->name('money.store');
        Route::get('/withdraw','FinancialController@withdraw')->name('money.withdraw');
        Route::post('/withdraw','FinancialController@withdrawStore')->name('money.withdraw.store');
        Route::get('/increase/credit/pay/{amount?}','FinancialController@pay')->name('money.pay');
        Route::post('/increase/credit/pay','FinancialController@payIt')->name('money.pay.online');
    });
    // Affiliate
    Route::group(['prefix'=>'affiliate'],function (){
        Route::get('/invite','AffliateController@index')->name('affiliate.invite');
        Route::get('/banner','AffliateController@banner')->name('affiliate.banner');
        Route::get('/report','AffliateController@report')->name('affiliate.report');
    });
    // Support
    Route::group(['prefix'=>'support'],function (){
        Route::get('/','SupportController@index')->name('support');

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/LinkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\link;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $links = Link::latest()->paginate(100);
        return view('Admin.Links.index',compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Links.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Link::create($request->only(['title','link','type']));
        alert()->success('تبریک!','لینک مورد نظر با موفقیت ایجاد شد !');
        return redirect(route('links.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\link  $link
     * @return \Illuminate\Http\Response
     */
    public function show(link $link)
    {
        return redirect(route('links.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\link  $link
     * @return \Illuminate\Http\Response
     */
    public function edit(link $link)
    {
        return view('Admin.Links.edit',compact('link'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\link  $link
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, link $link)
    {
        $link->update($request->only(['title','link','type']));
        alert()->success('تبریک!','لینک مورد نظر با موفقیت بروزرسانی شد !');
        return redirect(route('links.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\link $link
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(link $link)
    {
        $link->delete();
        alert()->warning('تبریک!','لینک مورد نظر با موفقیت حذف شد!');
        return redirect(route('links.index'));
    }
}

resources/views/Admin/Links/edit.blade.php
@extends('Admin.master')
@section('title','پیوند ها')
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">ویرایش پیوند</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('links.update',['link'=>$link->id]) }}" method="post">
            @csrf
            {{ method_field('PATCH') }}
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-6">
                        <label for="title">عنوان پیوند</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ $link->title ?? old('title') }}">
                    </div>
                    <div class="form-group col-6">
                        <label for="link">عنوان پیوند</label>
                        <input type="text" class="form-control" id="link" name="link" value="{{ $link->link ?? old('link') }}">
                    </div>
                    <div class="form-group col-12">
                        <label for="type">مکان نمایش</label>
                        <select class="form-control select2 w-100" id="type" name="type">
                            <option value="news" {{ $link->type == 'public' ? 'selected' : '' }}>اخبار</option>
                            <option value="public" {{ $link->type == 'news' ? 'selected' : '' }}>اعلان عمومی</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-success">ویرایش</button>
                <a href="{{ route('links.index') }}" class="btn btn-default float-left">بازگشت</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@stop
@section('script')
    <script src="{{ asset('admin/plugins/select2/select2.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/select2/i18n/fa.js') }}"></script>
    <script>
        $(function () {
            $('.select2').select2();
        });
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/select2.min.css') }}">
@stop

resources/views/Admin/Links/index.blade.php
@extends('Admin.master')
@section('title','پیوند ها')
@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3 class="card-title">آخرین پیوند ها</h3>
            <a href="{{ route('links.create') }}" class="btn btn-info">ایجاد</a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="datatable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>عنوان</th>
                    <th>نوع</th>
                    <th>آدرس پیوند</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($links as $link)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $link->title }}</td>
                        <td>{{ $link->type == 'public' ? 'عمومی' : 'اخبار' }}</td>
                        <td><a href="{{ url($link->link) }}">پیوند</a></td>
                        <td>
                            <form action="{{ route('links.destroy',['link'=>$link->id]) }}" method="post">
                                @csrf
                                {{ method_field('DELETE') }}
                                <a href="{{ route('links.edit',['link'=>$link->id]) }}" class="btn btn-warning btn-sm">ویرایش</a>
                                <button class="btn btn-danger btn-sm btn-ask" type="submit">حذف</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>عنوان</th>
                    <th>نوع</th>
                    <th>آدرس پیوند</th>
                    <th>تنظیمات</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@stop
@section('script')
    <script>
        $(function () {
            $("#datatable").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Persian.json"
                },
                "info" : false,
            });
        });
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.css') }}">
@stop

resources/views/Admin/Links/new.blade.php
@extends('Admin.master')
@section('title','پیوند ها')
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">پیوند جدید</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('links.store') }}" method="post">
            @csrf
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-6">
                        <label for="title">عنوان پیوند</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}">
                    </div>
                    <div class="form-group col-6">
                        <label for="link">آدرس پیوند</label>
                        <input type="url" class="form-control" id="link" name="link" value="{{ old('link') }}">
                    </div>
                    <div class="form-group col-12">
                        <label for="type">مکان نمایش</label>
                        <select class="form-control select2 w-100" id="type" name="type">
                            <option value="news" {{ old('type') == 'public' ? 'selected' : '' }}>اخبار</option>
                            <option value="public" {{ old('type') == 'news' ? 'selected' : '' }}>اعلان عمومی</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-success">ایجاد</button>
                <a href="{{ route('links.index') }}" class="btn btn-default float-left">بازگشت</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@stop
@section('script')
    <script src="{{ asset('admin/plugins/select2/select2.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/select2/i18n/fa.js') }}"></script>
    <script>
        $(function () {
            $('.select2').select2();
        });
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/select2.min.css') }}">
@stop