routes/web.php
<?php

// Admin Panel
Route::namespace('Admin')->prefix('admin')->middleware(['auth:web','admin','lastLogin'])->group(function () {
    Route::get('dashboard','AdminController@index')->name('adminDashboard');
    // Projects
    Route::resource('projects','ProjectController');
    Route::get('project/pending','ProjectController@pending')->name('projects.pending');
    Route::get('project/canceled','ProjectController@canceled')->name('projects.canceled');
    Route::get('project/closed','ProjectController@closed')->name('projects.closed');
    Route::patch('projects/active/{project}','ProjectController@confirm')->name('project.active');
    Route::patch('projects/deactivate/{project}','ProjectController@deactivate')->name('project.deactivate');
    Route::get('project/search','ProjectController@search')->name('projects.search');
    Route::post('project/search','ProjectController@searchPost')->name('projects.search.post');
    Route::delete('projects/offer/{offer}/delete','ProjectController@deleteOffer')->name('project.offer.delete');
    Route::patch('projects/offer/{offer}/assign','ProjectController@assign')->name('project.offer.assign');
    // Category
    Route::resource('categories','CategoryController');
    // Skills
    Route::resource('skills','SkillController');
    // Packages
    Route::resource('packages','PackageController');
    // Links
    Route::resource('links','LinkController');
    // Payment
    Route::get('payments','PaymentController@index')->name('payments.index');
    Route::get('payments/unsuccessful','PaymentController@unsuc')->name('payments.unsuc');
    Route::get('payments/successful','PaymentController@suc')->name('payments.suc');
    Route::get('payments/deposits','PaymentController@deposits')->name('payments.deposits');
    Route::get('payments/release','PaymentController@release')->name('payments.release');
    Route::get('withdraws','PaymentController@withdraws')->name('withdraws.index');
    Route::get('withdraws/pending','PaymentController@pending')->name('withdraws.pending');
    Route::get('withdraws/successful','PaymentController@successful')->name('withdraws.suc');
    Route::get('withdraws/canceled','PaymentController@canceled')->name('withdraws.canceled');
    Route::get('withdraws/{withdraw}','PaymentController@view')->name('withdraws.view');
    Route::patch('withdraws/{withdraw}','PaymentController@pay')->name('withdraws.pay');
    // Packages
    Route::resource('faqs','FaqController',['parameters' => [
        'faqs' => 'question'
    ]]);
    // Packages
    Route::resource('helps','HelpController',['parameters' => [
        'helps' => 'question'
    ]]);
    // Users
    Route::resource('users','UserController');
    Route::get('user/search','UserController@search')->name('users.search');
    Route::post('user/search','UserController@searchPost')->name('users.search.post');
    Route::patch('users/{user}/ban','UserController@ban')->name('users.ban');
    // Upload Files
    Route::group(['prefix'=>'uploadFile'],function (){
        // New Project
        Route::post('project','AdminController@projectUploadFile')->name('projectUploadFile');
    });
    // Site Settings
    Route::get('settings','SettingsController@index')->name('settings.index');
    Route::post('settings','SettingsController@update')->name('settings.update');
    // Site Settings
    Route::get('conversations','ConversationController@index')->name('conversation.index');
    Route::get('conversations/pending','ConversationController@pending')->name('conversation.pending');
    Route::get('conversations/rejected','ConversationController@rejected')->name('conversation.rejected');
    Route::patch('conversation/{conversation}/active','ConversationController@active')->name('conversation.active');
    Route::patch('conversation/{conversation}/reject','ConversationController@reject')->name('conversation.reject');
});

Route::namespace('User')->prefix('user')->middleware(['auth:web','lastLogin'])->group(function () {
    Route::get('dashboard','UserController@index')->name('userDashboard');
    // Project
    Route::get('project/new','ProjectController@index')->name('user.project.new');
    Route::post('project/new','ProjectController@store')->name('user.project.store');
    Route::get('project/{project}/edit','ProjectController@edit')->name('user.project.edit');
    Route::get('project/{project}/close','ProjectController@close')->name('user.project.close');
    Route::patch('project/{project}/update','ProjectController@update')->name('user.project.update');
    Route::post('project/new/categories','ProjectController@subcategory')->name('user.project.store.categories');
    Route::get('project/{project}','ProjectController@view')->name('user.project.view');
    // Deposit
    Route::get('project/{project}/deposits','ProjectController@deposit')->name('user.project.deposits');
    Route::patch('project/{project}/deposits','ProjectController@depositAction')->name('user.project.deposits.update');
    // Confirm
    Route::get('project/{project}/confirm','ProjectController@confirm')->name('project.confirm');
    // Release
    Route::get('project/{project}/release','ProjectController@release')->name('project.release');
    Route::patch('project/{project}/release','ProjectController@releaseAction')->name('project.release.update');
    // Make Vote
    Route::patch('project/{project}/vote','ProjectController@vote')->name('project.vote');
    // Project List
    Route::get('projects/all','ProjectController@all')->name('user.projects.all');
    Route::get('projects/urgent','ProjectController@urgent')->name('user.projects.urgent');
    Route::get('projects/special','ProjectController@special')->name('user.projects.special');
    Route::get('projects/related','ProjectController@related')->name('user.projects.related');
    Route::get('projects/hire','ProjectController@hire')->name('user.projects.hire');
    Route::get('projects/done','ProjectController@done')->name('user.projects.done');
    Route::post('projects/search','ProjectController@search')->name('user.projects.search');
    // Project Conversations Section
    Route::group(['prefix'=>'conversation'],function (){
        // Freelancer To Employer
        Route::get('/{project}','ProjectController@freelancerToEmployer')->name('conversations.fte');
        Route::post('/{project}','ProjectController@freelancerToEmployerStore')->name('conversations.fte.store');
        Route::get('/{project}/delete','ProjectController@freelancerToEmployerRemove')->name('conversations.fte.delete');
        // Employer To Freelancer
        Route::get('/{project}/{user}','ProjectController@employerToFreelancer')->name('conversations.etf');
        Route::post('/{project}/{user}','ProjectController@employerToFreelancerStore')->name('conversations.etf.store');
        // Accept Offer
        Route::patch('/{project}/{offer}/accept','ProjectController@acceptOffer')->name('project.accept.offer');
        // Pay Prepayment
        Route::get('/{project}/prepayment','ProjectController@employerPrepayment')->name('project.prepayment');
        // Pay Warranty
        Route::get('/{project}/warranty','ProjectController@freelancerWarranty')->name('project.warranty');
        // Convert To Hire
        Route::get('/{project}/make/hire','ProjectController@convertHire')->name('project.convert.hire');
        // Convert To Urgent
        Route::get('/{project}/make/urgent','ProjectController@convertUrgent')->name('project.convert.urgent');
        // Convert To Special
        Route::get('/{project}/make/special','ProjectController@convertSpecial')->name('project.convert.special');
        // Convert To Hidden
        Route::get('/{project}/make/hidden','ProjectController@convertHidden')->name('project.convert.hidden');
    });
    // Employer
    Route::get('employer/requests','EmployerController@index')->name('employer.requests');
    Route::post('employer/requests','EmployerController@filter')->name('employer.requests.filter');
    Route::get('employer/find','EmployerController@find')->name('employer.find');
    Route::post('employer/find','EmployerController@findFilter')->name('employer.find.filter');
    Route::get('employer/judgement','EmployerController@judge')->name('employer.judge');
    // Freelancer
    Route::get('freelancer/requests','FreelancerController@index')->name('freelancer.requests');
    Route::post('freelancer/requests','FreelancerController@filter')->name('freelancer.requests.filter');
    Route::get('freelancer/find','FreelancerController@find')->name('freelancer.find');
    Route::get('freelancer/judgement','FreelancerController@judge')->name('freelancer.judge');
    // Financial
    Route::group(['prefix'=>'financial'],function (){
        Route::get('/','FinancialController@index')->name('money.index');
        Route::get('/increase/credit','FinancialController@increase')->name('money.add');
        Route::get('/edit','FinancialController@edit')->name('money.edit');
        Route::post('/edit','FinancialController@store')->name('money.store');
        Route::get('/withdraw','FinancialController@withdraw')->name('money.withdraw');
        Route::post('/withdraw','FinancialController@withdrawStore')->name('money.withdraw.store');
        Route::get('/increase/credit/pay/{amount?}','FinancialController@pay')->name('money.pay');
        Route::post('/increase/credit/pay','FinancialController@payIt')->name('money.pay.online');
    });
    // Affiliate
    Route::group(['prefix'=>'affiliate'],function (){
        Route::get('/invite','AffliateController@index')->name('affiliate.invite');
        Route::get('/banner','AffliateController@banner')->name('affiliate.banner');
        Route::get('/report','AffliateController@report')->name('affiliate.report');
    });
    // Support
    Route::group(['prefix'=>'support'],function (){
        Route::get('/','SupportController@index')->name('support');

app/Package.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Package extends Model
{
    protected  $guarded = [];
    protected $appends = ['color','colorSecond'];

    public function getPriceAttribute($val)
    {
        return intval($val);
    }

    public function getColorAttribute()
    {
        if(Str::contains($this->icon,'free.png')){
            return 'blue';
        }elseif(Str::contains($this->icon,'bronze.png')){
            return 'bronze';
        }elseif(Str::contains($this->icon,'gold.png')){
            return 'gold';
        }else{
            return 'silver';
        }
    }

    public function getColorSecondAttribute()
    {
        if(Str::contains($this->icon,'free.png')){
            return 'info';
        }elseif(Str::contains($this->icon,'bronze.png')){
            return 'warning';
        }elseif(Str::contains($this->icon,'gold.png')){
            return 'danger';
        }else{
            return 'secondary';
        }
    }

    public function getFeaturesAttribute($val){
        return json_decode($val);
    }

    public function getIconAttribute($val){
        return asset('images/plan/'.$val);
    }

    protected $casts = [
        'features' => 'array',
    ];
}

app/Http/Controllers/Admin/PackageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Package;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PackageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $packages = Package::latest()->paginate(100);
        return view('Admin.Packages.index',compact('packages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Packages.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'length' => 'required|numeric',
            'icon' => 'required',
            'features.fee' => 'required|numeric',
            'features.max' => 'required',
            'features.portfolio' => 'required',
        ]);
        $price = 0;
        $default = 0;
        if($request->has('price') && intval($request->price) > 500){
            $price = $request->price;
        }else{
            $default = 1;
        }
        if($request->has('min') && intval($request->min) != 0){
            $min = intval($request->min);
        }else{
            $min = null;
        }
        $data = [
            'name' => $request->name,
            'price' => $price,
            'length' => $request->length,
            'icon' => $request->icon,
            'features' => [
                'max' => $request->input('features.max'),
                'fee' => $request->input('features.fee'),
                'portfolio' => $request->input('features.portfolio')
            ],
            'is_default' => $default,
            'min' => $min
        ];
        if($request->input('features.desc1')){
            $data['features']['desc1'] = $request->input('features.desc1');
        }
        if($request->input('features.desc2')){
            $data['features']['desc2'] = $request->input('features.desc2');
        }
        if($request->popular){
            $data['popular'] = true;
        }
        Package::create($data);
        alert()->success('عملیات موفق !','پکیج مورد نظر با موفقیت ایجاد شد !');
        return redirect()->route('packages.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function show(Package $package)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Package  $package
     * @return \Illuminate\Http\Response
     */
    public function edit(Package $package)
    {
        return view('Admin.Packages.edit',compact('package'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Package $package
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Package $package)
    {
        $this->validate($request,[
            'name' => 'required',
            'length' => 'required|numeric',
            'icon' => 'required',
            'features.fee' => 'required|numeric',
            'features.max' => 'required',
            'features.portfolio' => 'required',
        ]);
        $price = 0;
        $default = 0;
        if($request->has('price') && intval($request->price) > 500){
            $price = $request->price;
        }else{
            $default = 1;
        }
        if($request->has('min') && intval($request->min) != 0){
            $min = intval($request->min);
        }else{
            $min = null;
        }
        $data = [
            'name' => $request->name,
            'price' => $price,
            'length' => $request->length,
            'icon' => $request->icon,
            'features' => [
                'max' => $request->input('features.max'),
                'fee' => $request->input('features.fee'),
                'portfolio' => $request->input('features.portfolio')
            ],
            'is_default' => $default,
            'min' => $min
        ];
        if($request->input('features.desc1')){
            $data['features']['desc1'] = $request->input('features.desc1');
        }
        if($request->input('features.desc2')){
            $data['features']['desc2'] = $request->input('features.desc2');
        }
        if($request->popular){
            $data['popular'] = true;
        }
        $package->update($data);
        alert()->success('عملیات موفق !','پکیج مورد نظر با موفقیت بروزرسانی شد !');
        return redirect()->route('packages.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Package $package
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Package $package)
    {
        $package->delete();
        alert()->warning('عملیات موفق!','پکیج مورد نظر با موفقیت حذف شد !');
        return redirect()->route('packages.index');
    }
}

resources/views/Admin/Packages/edit.blade.php
@extends('Admin.master')
@section('title','پکیج ها')
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">پکیج جدید</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('packages.update',['package'=>$package->id]) }}" method="post">
            @csrf
            {{ method_field('PATCH') }}
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-6">
                        <label for="name">نام پکیج</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name') ?? $package->name }}">
                    </div>
                    <div class="form-group col-6">
                        <label for="price">قیمت (تومان)</label>
                        <input type="number" min="0" step="1000" class="form-control" value="{{ old('price') ?? $package->price }}" id="price" name="price">
                        <span class="text-mute form-text text-secondary small">وارد نکردن قیمت یا عدد 0 به عنوان رایگان ارائه میشود</span>
                    </div>
                    <div class="form-group col-6">
                        <label for="length">مدت زمان (روز)</label>
                        <input type="number" min="1" step="1" class="form-control" value="{{ old('length') ?? $package->length }}" id="length" name="length">
                    </div>
                    <div class="form-group col-6">
                        <label for="icon">آیکون</label>
                        <select class="form-control select2 w-100" id="icon" name="icon">
                            <option value="free.png" {{ old('icon') == 'free.png' || contains($package->icon,'free.png') ? 'selected' : '' }}>آبی</option>
                            <option value="silver.png" {{ old('icon') == 'silver.png' || contains($package->icon,'silver.png') ? 'selected' : '' }}>نقره ای</option>
                            <option value="bronze.png" {{ old('icon') == 'bronze.png' || contains($package->icon,'bronze.png') ? 'selected' : '' }}>برنزی</option>
                            <option value="gold.png" {{ old('icon') == 'gold.png' || contains($package->icon,'gold.png') ? 'selected' : '' }}>طلایی</option>
                        </select>
                    </div>
                    <div class="form-group col-6">
                        <label for="fee">کمیسیون سایت (درصد)</label>
                        <input type="number" min="1" class="form-control" id="fee" required name="features[fee]" value="{{ old('features.fee') ?? $package->features->fee }}">
                    </div>
                    <div class="form-group col-6">
                        <label for="max">انجام پروژه همزمان (حداکثر)</label>
                        <input type="number" min="-1" class="form-control" id="max" required name="features[max]" value="{{ old('features.max') ?? $package->features->max }}">
                        <span class="text-mute form-text text-secondary small">عدد -1 به معنای نامحدود میباشد !</span>
                    </div>
                    <div class="form-group col-6">
                        <label for="portfolio">تعداد نمونه کار ها ( حداکثر)</label>
                        <input type="number" min="-1" class="form-control" id="portfolio" required name="features[portfolio]" value="{{ old('features.portfolio') ?? $package->features->portfolio }}">
                        <span class="text-mute form-text text-secondary small">عدد -1 به معنای نامحدود میباشد !</span>
                    </div>
                    <div class="form-group col-6">
                        <label for="desc1">توضیح دلخواه شماره اول</label>
                        <input type="text" class="form-control" id="desc1" name="features[desc1]" value="{{ old('features.desc1') ?? $package->features->desc1 }}">
                        <span class="text-mute form-text text-secondary small">این توضیحات به عنوان آیتم در صفحه پکیج ها نمایش داده میشود</span>
                    </div>
                    <div class="form-group col-6">
                        <label for="desc2">توضیح دلخواه شماره دوم</label>
                        <input type="text" class="form-control" id="desc2" name="features[desc2]" value="{{ old('features.desc2') ?? $package->features->desc2 }}">
                        <span class="text-mute form-text text-secondary small">این توضیحات به عنوان آیتم در صفحه پکیج ها نمایش داده میشود</span>
                    </div>
                    <div class="form-group col-6">
                        <label for="popular">پکیج محبوب شود ؟</label>
                        <div>
                            <input type="checkbox" name="popular" id="popular" {{ old('popular') || boolval($package->popular) ? 'checked' : '' }}>
                            <label for="popular">
                                محبوب
                            </label>
                        </div>
                    </div>
                    <div class="form-group col-12">
                        <label for="min">حداقل پروژه های انجام شده</label>
                        <input type="number" min="0" step="1" class="form-control" value="{{ old('min') ?? $package->min }}" id="min" name="min">
                        <span class="text-mute form-text text-secondary small">حداقل پروژه هایی که کاربر باید انجام داده باشد تا بتواند این پلن را خریداری کند ( عدد 0 یا وارد نکردن به معنای این میباشد که برای عموم آزاد است )</span>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-success">بروزرسانی</button>
                <a href="{{ route('packages.index') }}" class="btn btn-default float-left">بازگشت</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@stop
@section('script')
    <script src="{{ asset('admin/plugins/select2/select2.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/select2/i18n/fa.js') }}"></script>
    <script src="{{ asset('admin/plugins/iCheck/icheck.min.js') }}"></script>
    <script>
        $(function () {
            $('.select2').select2();
            $('input[type="checkbox"]').each(function(){
                var self = $(this),
                    label = self.next(),
                    label_text = label.text();

                label.remove();
                self.iCheck({
                    checkboxClass: 'icheckbox_line-green py-2',
                    radioClass: 'iradio_line-green',
                    insert: '<div class="icheck_line-icon"></div>' + label_text
                });
            });
        });
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/iCheck/all.css') }}">
@stop

resources/views/Admin/Packages/index.blade.php
@extends('Admin.master')
@section('title','پکیج ها')
@section('content')
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <h3 class="card-title">آخرین پکیج ها</h3>
            <a href="{{ route('packages.create') }}" class="btn btn-info">ایجاد</a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="datatable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>عنوان</th>
                    <th>قیمت</th>
                    <th>مدت</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($packages as $package)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td data-toggle="tooltip" title="{{ $package->name }}">{{ limit($package->name,20) }}</td>
                            <td>{{ money($package->price) }}</td>
                            <td><span class="badge badge-primary">{{ $package->length }} روز </span></td>
                            <td>
                                <form action="{{ route('packages.destroy',['package'=>$package->id]) }}" method="post">
                                    @csrf
                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('packages.edit',['package'=>$package->id]) }}" class="btn btn-warning btn-sm">ویرایش</a>
                                    <button class="btn btn-danger btn-sm btn-ask" type="submit">حذف</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>عنوان</th>
                    <th>قیمت</th>
                    <th>مدت</th>
                    <th>تنظیمات</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
@stop
@section('script')
    <script>
        $(function () {
            $("#datatable").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Persian.json"
                },
                "info" : false,
            });
        });
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.css') }}">
@stop